#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.1 on Mon Feb 18 11:19:47 2019
#
import wx
from loadConfig import loadConfig 
import BIOSUP

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class GUI_Window(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GUI_Window.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.config = loadConfig("GUI_config.ini")
        self.SetSize((400, 300))
        self.AMD_Chq_List = wx.CheckListBox(self, wx.ID_ANY, choices=self.config.AMDallowedchipsets)
        self.Intel_Chq_List = wx.CheckListBox(self, wx.ID_ANY, choices=self.config.INTELallowedchipsets)
        self.Vendor_Chq_List = wx.CheckListBox(self, wx.ID_ANY, choices=self.config.vendor)
        self.Run_Btn = wx.Button(self, wx.ID_ANY, "Run")
        self.Selectall_Btn = wx.Button(self,wx.ID_ANY,"Select All")
        self.useLast_Btn = wx.CheckBox(self,wx.ID_ANY,"Run last config")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.Run_Btn.Bind(wx.EVT_BUTTON, self.Run_Event)
        self.Selectall_Btn.Bind(wx.EVT_BUTTON, self.Select_All_Chq_Box)
        self.useLast_Btn.Bind(wx.EVT_BUTTON, self.Select_Last_Run)

        self.useLast_Btn.SetValue(True)

    def __set_properties(self):
        # begin wxGlade: GUI_Window.__set_properties
        self.SetTitle("BIOSUP")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GUI_Window.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Vendors"), wx.VERTICAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Intel Chipsets"), wx.VERTICAL)
        sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "AMD Chipsets"), wx.VERTICAL)
        sizer_1.Add(self.AMD_Chq_List, 0, 0, 0)
        grid_sizer_1.Add(sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.Intel_Chq_List, 0, 0, 0)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(self.Vendor_Chq_List, 0, 0, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.Selectall_Btn, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.useLast_Btn, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.Run_Btn, 0, wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.SetSizer(grid_sizer_1)
        self.Layout()
        # end wxGlade
    
    def Run_Event(self, evt):
        print("Running BIOSUP")
        if self.useLast_Btn.IsChecked():
            print("I am checked")
        else:
            print("Not Checked")

    def Select_All_Chq_Box(self, evt): 
        print("Selecting all tick boxes")
        self.AMD_Chq_List.SetCheckedStrings(self.config.AMDallowedchipsets)
        self.Intel_Chq_List.SetCheckedStrings(self.config.INTELallowedchipsets)
        self.Vendor_Chq_List.SetCheckedStrings(self.config.vendor)

    def Select_Last_Run(self, evt):
        print("Loading last run")
# end of class GUI_Window

class MyApp(wx.App):
    def OnInit(self):
        self.GUI_FRAME = GUI_Window(None, wx.ID_ANY, "")
        self.SetTopWindow(self.GUI_FRAME)
        self.GUI_FRAME.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
